name: github-actions-develop
on:
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project sources
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - run: echo "setting before build and test is finished"

      - name: setup gradle
        uses: gradle/gradle-build-action@v2
      - name: build step
        run:
          ./gradlew build
      - name: test step
        run:
          ./gradlew test

      - run: echo "🎉 build and test success"
      - run: echo "Press button 'Merge pull request' and Check next workflow"